import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import 'bootstrap-icons/font/bootstrap-icons.json'
import './globals.css'
import { MenuLateral } from '../components/MenuLateral'
import { Navegador } from '../components/Navegador'
import { UseProvider } from './contexts/UsuarioContext'

export const metadata: Metadata = {
  title: 'METARH CONECTA',
  description: 'Generated by create next app',
  icons: {
    icon: '/LOGO-BRANCO.ico',
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR" data-lt-installed="true" suppressHydrationWarning>
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css"
        />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body suppressHydrationWarning className="relative col-span-2 grid">
        <UseProvider>{children}</UseProvider>
      </body>
    </html>
  )
}
