import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import 'bootstrap-icons/font/bootstrap-icons.json'
import { MenuLateral } from '@/src/components/MenuLateral'
import { Navegador } from '@/src/components/Navegador'
export const metadata: Metadata = {
  title: 'Meta RH',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <MenuLateral />
      <Navegador />
      {children}
    </>
  )
}
